# Generated by Django 5.0.1 on 2024-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_note'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='core_note_title_25b1b2_idx'),
        ),
    ]
